INSERT INTO HR.BUS(ID, BUS_TYPE, SEAT_COUNT) VALUES (hibernate_sequence.NEXTVAL, 'TYPE1', 10);
INSERT INTO HR.BUS(ID, BUS_TYPE, SEAT_COUNT) VALUES (hibernate_sequence.NEXTVAL, 'TYPE2', 20);
INSERT INTO HR.BUS(ID, BUS_TYPE, SEAT_COUNT) VALUES (hibernate_sequence.NEXTVAL, 'TYPE3', 30);
