INSERT INTO HR.BUS(ID, BUS_TYPE, MAX_SEATS, MAX_BIKES) VALUES (hibernate_sequence.NEXTVAL, 'A-type', 10, 1);
INSERT INTO HR.BUS(ID, BUS_TYPE, MAX_SEATS, MAX_BIKES) VALUES (hibernate_sequence.NEXTVAL, 'B-type', 20, 2);
INSERT INTO HR.BUS(ID, BUS_TYPE, MAX_SEATS, MAX_BIKES) VALUES (hibernate_sequence.NEXTVAL, 'C-type', 30, 3);
