INSERT INTO HR.BUS(ID, BUS_TYPE, MAX_SEATS) VALUES (hibernate_sequence.NEXTVAL, 'A-type', 10);
INSERT INTO HR.BUS(ID, BUS_TYPE, MAX_SEATS) VALUES (hibernate_sequence.NEXTVAL, 'B-type', 20);
INSERT INTO HR.BUS(ID, BUS_TYPE, MAX_SEATS) VALUES (hibernate_sequence.NEXTVAL, 'C-type', 30);
